var notebooks = angular.module('notebooks', []);

notebooks.controller('NotebookListCtrl', function($scope) {
  $scope.notebooks = [
    {"name": "Valerie",
     "procesor": "Amy Winehouse",
     "age": 2011},
     {"name": "Jolene",
     "procesor": "Dolly Parton",
     "age": 2011},
     {"name": "Just A Girl",
     "procesor": "No Doubt",
     "age": 2011},
     {"name": "Ain't It Fun",
     "procesor": "Paramore",
     "age": 2011},
     {"name": "Magic Man",
     "procesor": "Heart",
     "age": 2011},
     {"name": "I Will survive",
     "procesor": "Gloria Gaynor",
     "age": 2011},
     {"name": "What's Up",
     "procesor": "4 Non Blondes",
     "age": 2011},
     {"name": "You Oughta Know",
     "procesor": "Alanis Morrisette",
     "age": 2011},
     {"name": "Creep",
     "procesor": "Radiohead",
     "age": 2011},
     {"name": "Zombie",
     "procesor": "The Cranberries",
     "age": 2011},
     {"name": "September",
     "procesor": "Earth, Wind, & Fire",
     "age": 2011},
     {"name": "Dreams",
     "procesor": "Fleetwood Mac",
     "age": 2011},
     {"name": "Sex On Fire",
     "procesor": "Kings of Leon",
     "age": 2011},
     {"name": "Santeria",
     "procesor": "Sublime",
     "age": 2011},
     {"name": "Purple Rain",
     "procesor": "Prince",
     "age": 2011},
     {"name": "Rock With You",
     "procesor": "Michael Jackson",
     "age": 2011},
     {"name": "Give Me One Reason",
     "procesor": "Tracy Chapman",
     "age": 2011},
     {"name": "Como La Flor",
     "procesor": "Selena",
     "age": 2011},
     {"name": "Bidi Bidi Bom Bom",
     "procesor": "Selena",
     "age": 2011},
     {"name": "Boogie Oogie",
     "procesor": "Taste Of Honey",
     "age": 2011},
     {"name": "Poison",
     "procesor": "Bell biv Devoe",
     "age": 2011},
     {"name": "What I Got",
     "procesor": "Sublime",
     "age": 2011},
     {"name": "Careless Whisper",
     "procesor": "George Michael",
     "age": 2011},
     {"name": "Hand In My Pocket",
     "procesor": "Alanis Morissette",
     "age": 2011},
     {"name": "Love On The Brain",
     "procesor": "Rhianna",
     "age": 2011},
     {"name": "Rhiannon",
     "procesor": "Fleetwood Mac",
     "age": 2011},
     {"name": "Bennie And The Jets",
     "procesor": "Elton John",
     "age": 2011},
     {"name": "I Wish",
     "procesor": "Stevie Wonder",
     "age": 2011},
     {"name": "Crazy",
     "procesor": "Gnarles Barkley",
     "age": 2011},
     {"name": "What A Fool Believes",
     "procesor": "The Doobie Brothers",
     "age": 2011},
     {"name": "Wasn't Me",
     "procesor": "Shaggy",
     "age": 2011},
     {"name": "Billie Jean",
     "procesor": "Michael Jackson",
     "age": 2011},
     {"name": "Make Me Wanna",
     "procesor": "Thomas Rhett",
     "age": 2011},
     {"name": "Drive",
     "procesor": "Incubus",
     "age": 2011},
     {"name": "Can't Stop",
      "procesor": "Red Hot Chili Peppers",
     "age": 2011},
     {"name": "Little Red Corvette",
     "procesor": "Prince",
     "age": 2011},
     {"name": "Everybody Want's To Rule The World",
     "procesor": "Tears For Fears",
     "age": 2011},
     {"name": "Tennessee Whiskey",
     "procesor": "Chris Stapleton",
     "age": 2011},
     {"name": "Baila Esta Cumbia",
     "procesor": "Selena",
     "age": 2011},
     {"name": "Juice",
     "procesor": "Lizzo",
     "age": 2011},
     {"name": "Locked Out Of Heaven",
     "procesor": "Bruno Mars",
     "age": 2011},
     {"name": "Sunday Morning",
     "procesor": "No Doubt",
     "age": 2011},
     {"name": "Edge Of Seventeen",
     "procesor": "Stevie Nicks",
     "age": 2011},
     {"name": "Mr. Brightside",
     "procesor": "The Killers",
     "age": 2011},
     {"name": "Fully Alive",
     "procesor": "Flyleaf",
     "age": 2011},
     {"name": "My Own Worst Enemy",
     "procesor": "LIT",
     "age": 2011},
     {"name": "Badfish",
     "procesor": "Sublime",
     "age": 2011},
     {"name": "Come And Get Your Love",
     "procesor": "Redbone",
     "age": 2011},
     {"name": "Pony",
     "procesor": "Ginuine",
     "age": 2011},
     {"name": "Scrubs",
     "procesor": "TLC",
     "age": 2011},
     {"name": "Killing Me Softly",
     "procesor": "Fugees",
     "age": 2011},
     {"name": "Gravity",
     "procesor": "John Mayer",
     "age": 2011},
     {"name": "Just Like Heaven",
     "procesor": "The Cure",
     "age": 2011},
     {"name": "I Just Wanna Fly",
     "procesor": "Sugar Ray",
     "age": 2011},
     {"name": "Hotel California",
     "procesor": "The Eagles",
     "age": 2011},
     {"name": "If I Ain't Got You",
     "procesor": "Alicia Keys",
     "age": 2011},
     {"name": "Superstition",
     "procesor": "Stevie Wonder",
     "age": 2011},
     {"name": "Redbone",
     "procesor": "Childish Gambino",
     "age": 2011},
     {"name": "What You Won't Do For Love",
     "procesor": "Bobby Caldwell",
     "age": 2011},
     {"name": "Just The Two Of Us",
     "procesor": "Bill Whithers",
     "age": 2011},
     {"name": "Mary Janes Last Dance",
     "procesor": "Tom Petty",
     "age": 2011},
     {"name": "Red Hot Chili Peppers",
     "procesor": "Dani California",
     "age": 2011},
     {"name": "Heaven",
     "procesor": "Los Loney Boys",
     "age": 2011},
     {"name": "Seven Nation Army",
     "procesor": "The White Stripes",
     "age": 2011},

  


     
     
     
     

     

     
     


     

  ];
  $scope.orderList = "name";
});